[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
swap = "5G8kSEHwJ8ofQdc7MBJee9Wn1XogYuiAK1cesU4K2moc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
